### ISSUE TITLE
Fix several issues reported by the validatior

### ISSUE THREAD

**Issue by m-mohr** [Open-EO/openeo-geopyspark-driver#10]
@bgoesswe deployed the Go validation tool for back-ends. The results for the geopyspark back-end can be found here:
https://www.geo.tuwien.ac.at/openeoct/backend/validate/3

There are several issues reported: 
- [x] http://openeo.vgt.vito.be/openeo/0.4.0 returns something different than http://openeo.vgt.vito.be/openeo/0.4.0/
- [x] `title` in `GET /` is missing
- [x] Your collections contain invalid datetimes (i.e. only the date, but missing the time). Make sure they are RFC3339 compliant (e.g. 2019-01-01T12:00:00Z)
- [x] `GET /jobs` returns "Usage: Create a new batch processing job using POST" instead of a list of jobs (but it is advertised in `GET /` to be supported).
- [x] `GET /output_formats` seems to still return a response compatible only to API v0.3. Basically, just move the value for formats to the root level and remove the property default.
- [x] `GET /services` returns an invalid response.

**Comment by soxofaan** [comment]
Some (more) issues I found for http://openeo.vgt.vito.be/openeo/0.4.0 with the pytest based test suite:

- [ ] CORS related OPTIONS requests to e.g. `/`  return with 200 code while it should be 204 (https://open-eo.github.io/openeo-api/cors/)
- [ ] `GET /services`  without authentication returns with 200 instead of 401 (unauthorized)
- [ ] `GET /jobs`  without authentication returns with 200 instead of 401 (unauthorized)
- [ ] `GET /invalid/path/foobar`  has no  `code` field in error response  (https://open-eo.github.io/openeo-api/errors/)
- [ ] `GET /collections/invalid-collection-name-foobar` has no  `code` field in error response  (https://open-eo.github.io/openeo-api/errors/)
- [ ] `GET /collections` : 'stac_version' is a required property (on collection "S2_FAPAR_SCENECLASSIFICATION_V102_PYRAMID")
- [ ] `GET /.well-known/openeo` returns with 404

**Comment by soxofaan** [comment]
I also think this issue should be moved to https://github.com/Open-EO/openeo-python-driver  because most REST API aspects are handled there
(I tried it myself, but it seems I can only transfer it to openeo-python-client repo)

**Comment by soxofaan** [comment]
there is already a PR with a batch of fixes for the reported problems here: https://github.com/Open-EO/openeo-python-driver/pull/5

**Comment by soxofaan** [comment]
Already checked some checkboxes handled by Open-EO/openeo-python-driver#5

(most of these still have to be deployed atm however)

**Comment by m-mohr** [comment]
One additional note: `title` in `GET /` is set to `openEO API`, which is not very meaningful. Could you change it to something like `VITO GeoPySpark` or so? Otherwise it leads to quite confusing result on http://hub.openeo.org/

**Comment by soxofaan** [comment]
(checked a couple of boxes above for issues that were already resolved)

**Comment by soxofaan** [comment]
now also fixed the issue about rfc3339 dates.

Now that all checkboxes are ticker: will close this ticket now.

There will probably more validation issues, but let's keep that for another ticket instead
