### ISSUE TITLE
CRS is given in wrong format

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-geopyspark-driver#120]
When looking at the details of a collection, e.g. https://openeo.vito.be/openeo/collections/S1_GRD_SIGMA0_ASCENDING, the `coordinate_system` key within `cube:dimensions.x` (and `.y`) contains a complex object instead of just an EPSG code or WKT2 string as dictated by the API spec:

> ![grafik](https://user-images.githubusercontent.com/17781682/145897175-6e024da0-f742-492a-8769-6de4fb1ecebd.png)

https://openeo.org/documentation/1.0/developers/api/reference.html#operation/describe-collection

With the help of another gotcha (one of the keys of that complex object containing a `$` sign which is special to MongoDB) this results in Open-EO/openeo-hub#90.

**Comment by m-mohr** [comment]
The API spec is outdated, I have to update that. That't what you get if you try to be nice to implementors and give as many "options" as you can instead of just referring to other specification. Now the field definition is outdated for the data cube definition as STAC now allows PROJJSON instead of PROJ strings.
