### ISSUE TITLE
creodias spark_tmp disks fill up and cause unstability

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#214]
This is how batch jobs temporary directories are now configured:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/deploy/sparkapplication.yaml.j2#L77

If we can introduce the job name in the host path, we could more easily clean up these temporary files when a job is fully finished.

There is already some code to handle finished jobs:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/job_tracker.py#L102

So the cleanup can also be triggered there.

One problem is: how can we handle clean up on the actual k8s hosts? The driver does not have access.

Other option is experimenting with pvc's, but that did not work last time we tried.

**Comment by JeroenVerstraelen** [comment]
Created a temp directory per job under /opt/{job_id}. There was an issue that this directory would be created as root user, so the user in the container could not write to it. However this was solved by using initContainers:
https://github.com/Open-EO/openeo-geopyspark-driver/commit/55fb6b55a6bf1071e4ff5b67e5dec6ae389bb776

This fix is currently waiting on the integration tests to be fixed before it can be deployed to the kubernetes cluster.

I also added a test to the config file of the driver to see if the initContainers solution will surely work, but that commit is waiting on the openeo-deploy-dias build to be fixed before it can be deployed to the cluster.

**Comment by JeroenVerstraelen** [comment]
I found out you can use the pod lifecycle feature of kubernetes to clear the directory.

So Instead of using a call from the driver when a job is finished at:
https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/openeogeotrellis/job_tracker.py#L102

The /opt/{job_id} is now emptied:
https://github.com/Open-EO/openeo-geopyspark-driver/commit/a6b863d2cbdce9d377185357a1cb587e20076111

We can then add a cronjob that on every node that removes all empty and old directories.
