### ISSUE TITLE
record synchronous job usage in marketplace

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#273]
/result calls are not recorded yet in marketplace. 
Main reason is we don't know typical cpu and memory usage.
We do record sentinelhub usage and inputpixels, so perhaps can define something based on that.

Retrieving cpu seems hard: start by reporting 5 credits per synchronous call.

**Comment by bossie** [comment]
ETL API indeed supports logging "processing" resources in "credits" as well as "shpu": https://etl.terrascope.be/docs/#/resources/ResourcesController_upsertResource

**Comment by bossie** [comment]
... but not in a single request, it seems: it's either a "processing" property with "unit": "credits" or a "processing" property with "unit": "shpu".

@JanssenBrm?

**Comment by jdries** [comment]
I think we just need two requests if we have both? The reporting will then add up all costs logged for a job?

**Comment by bossie** [comment]
Yes, that was my assumption as well.

**Comment by bossie** [comment]
I can send two requests but in this case, it seems to require different `jobId`s (`jobId` becomes part of the document's `_id`).

I'm not sure how that works if we take into account that OpenEO batch jobs can be restarted (the `jobId` remains the same but the `executionId` is different).

**Comment by JanssenBrm** [comment]
Thanks for the good analysis guys! It looks like the API is indeed not fully matching with the expected situation here. I think there are 2 issues here:

**Registering of synchronous calls**

We do have a `/service/openeo` endpoint that is used by the TerraScope openEO environment to log synchronous calls. This endpoint will just deduct a fixed amount of credits and does not allow you to specify any additional credits to be deducted. 

However, due to its limits, it could make sense to use the `/resources/` endpoint. However, this endpoint indeed limits the `processing` property to only a single value. We can take a look at adapting this as this could make sense in future use cases as well.


**Construction of the document ID**

If I understood correctly from @bossie 's last comment, is that restarting an openEO batch job will launch the job with the same `jobId` but a different `executionId`. If my understanding is correct, it could make sense to change the construction of the document ID in elasticsearch to use the `executionId` iso the `jobId`. Would this logic work better?

**Comment by bossie** [comment]
That summarizes it well. :+1:

**Comment by bossie** [comment]
As discussed, the `executionId` can differentiate between different attempts of a batch job and their respective usage so it does make sense to use `executionId` rather than `jobId` in the document ID.

**Comment by bossie** [comment]
Implemented by defaulting to 1 CPU-hour and 2 GB-hours (see https://github.com/eu-cdse/openeo-cdse-infra/issues/35).
