### ISSUE TITLE
issue in hillshade udf

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#309]
https://github.com/DHI-GRAS/worldwater-toolbox/blob/main/openeo_platform_notebooks/hillshade-UDF-example.ipynb

hillshaded = merged_cube.apply_neighborhood(process=process,

                                            size=[{"dimension":"t","value": "P1D"},

                                                  {"dimension": "x", "unit": "px", "value": 256},

                                                  {"dimension": "y", "unit": "px", "value": 256}],

                                            overlap=[{"dimension": "x", "unit": "px", "value": "8"},

                                                     {"dimension": "y", "unit": "px", "value": "8"}])

 

The UDF now works and indeed the borders between tiles are not visible anymore. But the other issue with artefacts unfortunately still remains. Below apply_neighborhood output is on top and apply at the bottom:

![Image](https://user-images.githubusercontent.com/5937096/212040743-69d9529b-c6b5-42e5-b200-f3d3432463e2.png)

![Image](https://user-images.githubusercontent.com/5937096/212040816-dbe080a7-0bdd-4a8b-b754-adb95ccd3b6d.png)

Note that we could also implement a similar hillshade using geotrellis:
https://github.com/locationtech/geotrellis/blob/master/raster/src/main/scala/geotrellis/raster/mapalgebra/focal/hillshade/Hillshade.scala

**Comment by jdries** [comment]
Debugging tip: start by applying udf with overlap set to 0, or even a simple 'apply' call.

**Comment by JeroenVerstraelen** [comment]
The hillshade algorithm is quite heavily dependant on neighbouring pixels:
```
Calculate a shaded region for elevation_model[ystart:yend] by looping over every
pixel of the elevation model and tracing the path towards the sun until an obstacle is
hit or the maximum elevation of the model is reached. The path is defined by a rasterized
direction of the sun ray in the xy-plane (ray) and the zenith.
```

I was able to reproduce the artifacts with a local python script. The script loads in the geotiff, divides it into 256x256 chunks and then executes the hillshade algorithm on every chunk. So it appears the artifacts are just a natural consequence of executing the hillshade algorithm on chunked data.

The top image is from our backend, the bottom one is from a local python script:
![Image](https://user-images.githubusercontent.com/3028262/215156665-0dea78fc-884b-4f44-9c7c-22edd65cb705.png)
![Image](https://user-images.githubusercontent.com/3028262/215157062-31de204f-2358-48d8-bc64-232acbbe2c14.png)

**Comment by jdries** [comment]
Does this perhaps mean that overlaps settings in apply_neighboorhood are not correct or not respected in the backend? These normally take care of ensuring that there's sufficient neighbouring pixels.

**Comment by JeroenVerstraelen** [comment]
The images in your original post show apply_neighborhood (with 8 pixel overlap) on top and apply on the bottom. I had similar results in my tests. It appears that an 8 pixel overlap removes most artifacts. Meanwhile apply and apply_neighborhood with 0 overlap return identical results with artifacts. 

So I believe the overlap settings in apply_neighborhood are correct. I don't know how the issue was first raised but it appears that they already solved it by using an 8 pixel overlap?

**Comment by JeroenVerstraelen** [comment]
Some very steep elevations require an overlap that is more than 8 pixels. You can see it in these images:

1. 8 pixel overlap
2. 16 pixel overlap
3. 32 pixel overlap
4. Ground truth (local execution of hillshade algorithm on entire geotiff)

![Image](https://user-images.githubusercontent.com/3028262/215264374-4aafeef5-e84c-4d49-b234-954bcd9f04bd.png)
![Image](https://user-images.githubusercontent.com/3028262/215264615-76b2f94d-63f6-482d-8b05-b3ff6d0c94c4.png)
![Image](https://user-images.githubusercontent.com/3028262/215264765-fcd4cac0-3683-4ef5-bf45-9a494da56f4a.png)
![Image](https://user-images.githubusercontent.com/3028262/215264376-4e1efab8-cdf2-4840-90da-1ef5f1127406.png)

These images also prove that the overlap settings are working as intended

**Comment by radosuav** [comment]
Thanks for looking into this @jdries and @JeroenVerstraelen. The border issue we indeed solved by using an 8-pixel overlap (see second last cell in https://github.com/DHI-GRAS/worldwater-toolbox/blob/main/openeo_platform_notebooks/hillshade-UDF-example.ipynb). 

The problem is with the horizontal and vertical stripes in the output shadow map. When I run the notebook with 60 m resolution (I select B01 as the first band to be read from SENTINEL_2_L2A_SENTINELHUB collection) the output looks fine (see below). But when I run the same notebook at 10 m resolution (selected B03 band) then there are artifacts in the output shadow mask.
![image](https://user-images.githubusercontent.com/4759850/217262626-561d8339-305b-4135-ab00-8a8573320d88.png)

Could those artifacts be somehow caused by the COPERNICUS_30 DEM being resampled to 10 m by OpenEO Platform?

**Comment by JeroenVerstraelen** [comment]
@radosuav When I generate only the merged cube the output of the SENTINEL_2_L2A_SENTINELHUB:B03 and DEM layer appear to be correct with no artifacts:
[generate_merged_cube.py](https://gist.github.com/JeroenVerstraelen/f4ca62ffa8b0f8fc79e830694c917a35)

B03 output of the previous gist:
![Screenshot from 2023-02-15 11-52-33](https://user-images.githubusercontent.com/3028262/219007744-26f81e0a-614b-41f5-8474-117603b62c08.png)
DEM output of the previous gist (resampled from 30m to 10m):
![Screenshot from 2023-02-15 11-50-29](https://user-images.githubusercontent.com/3028262/219007300-6b1bf805-922d-433a-b234-281566342c03.png)

When I provide this merged_cube.tif to a local version of your hillshade_UDF.py script I receive the same output as on openEO:
[local_hillshade.py](https://gist.github.com/JeroenVerstraelen/53db2b445250bfd66f262fc9a027f0ed)
![Screenshot from 2023-02-15 12-00-08](https://user-images.githubusercontent.com/3028262/219009541-0b39c4a2-8af3-4e82-b330-a901e2bfd355.png)

So it looks like these artifacts are caused by the hillshade library itself.
