### ISSUE TITLE
integrate proba-v collection 2

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#358]

**Comment by JeroenVerstraelen** [comment]
@jdries Is it possible to get some more information on this issue?

**Comment by jdries** [comment]
https://proba-v.vgt.vito.be/en/proba-v-collection-2-reprocessing-campaign
Best to check internally with Lieve, we need to replace/update existing PROBA layers.

**Comment by JeroenVerstraelen** [comment]
@jdries The PR on bitbucket is ready, after a discussion with Lieve we are not sure if there are still users for the probav-c1 layer on the timeseries service. So instead of replacing it we might actually be able to remove it.

**Comment by JeroenVerstraelen** [comment]
We chose not to remove the probav layers from the TS service. They have now  also been adjusted and will be available on the next production deployment. I will test them in the development environment first.

**Comment by JeroenVerstraelen** [comment]
I did a thorough check on the ProbaV data using Qgis and Gdal and deployed the new layers to production. 

I was confused at first because for some bands the original tiles show up as float32 data in Qgis where we use uint8 or uint16. I double checked by manually converting the raster data using the python gdal library and the provided scaling and offset values. All bands match the original data and are in the right location of the output tiff. The output data is shifted by about half a pixel but that should be normal.
