### ISSUE TITLE
add load_stac process

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#402]
https://processes.openeo.org/draft/#load_stac

This probably has a lot in common with load_result.
There is one important change: we want to use FileLayerProvider, with a STAC client.

Specific case:
 STAC API Collection that allows to filter items and to download assets.

**Comment by bossie** [comment]
Differences with `load_result`:
- only accepts URLs, not batch job IDs
- supports`properties` argument

**Comment by bossie** [comment]
From the process description:

> Batch job results can be specified in two ways:
>
> For Batch job results at the same back-end, a URL pointing to the corresponding batch job results endpoint should be provided. The URL usually ends with /jobs/{id}/results and {id} is the corresponding batch job ID.
> For external results, a signed URL must be provided. Not all back-ends support signed URLs, which are provided as a link with the link relation canonical in the batch job result metadata.

@jdries does this imply that the logged-in user should be able load his own batch job results by providing a /jobs/{id}/results URL that is not signed?

**Comment by jdries** [comment]
Good question, because I thought the canonical link was the only way to retrieve the correct url, but I think that this is indeed implied here. Note that for this ticket, implementing the remote url option is actually the main goal.

**Comment by soxofaan** [comment]
> @jdries does this imply that the logged-in user should be able load his own batch job results by providing a /jobs/{id}/results URL that is not signed?

Indeed, I pushed for that because the signed URLs have an expiry, could be invalidated/rotated, ..., while the `/jobs/{id}/results` URL is static and easily predictable (but require auth headers). I think both options are valuable to have (for different use cases)

**Comment by bossie** [comment]
It looks like that, at some point in the code, we have to determine whether the provided URL represents a static STAC catalog (incl. batch job results) or a dynamic STAC API Collection (which supports search requests).

A possible way to accomplish this seems to consist of:
- fetching the STAC Collection document that the URL points to;
- fetching the Collection's root Catalog by navigating to its "root" link;
- looking at the root Catalog document's "conformsTo" property to determine whether it's a STAC API that supports item search;
- if it does, we can send search requests to the Catalog's "search" URL for this collection; otherwise it's a static Catalog and we browse it.

@m-mohr does this approach seem right to you?

**Comment by m-mohr** [comment]
Sounds reasonable.

**Comment by bossie** [comment]
The intended STAC API is not available yet but I've been working on loading static STAC Catalogs/Collections/Items. That went well until I tried to load (the canonical link to) batch job results (= an example of said STAC Collections).

It seems the `FileLayerProvider` is currently tailored towards features with single band assets, of which the asset ID matches the band name. This seems to be the case for a lot of catalogs but not (rightfully so) for the assets in our batch job results, so this Did Not Work, and the original use case (a STAC API) will probably also Not Work Yet if it produces multiband assets.

I have since come up with a way to make the `FileLayerProvider` work with multiband assets but it's patched on and needs a lot of cleaning up, as does the `load_stac` implementation in the Python code, which has lots of code duplication.

Then there are a few assumptions in the code that might not always hold, `load_stac`'s `properties` argument is not supported yet and our own batch jobs need some special treatment as described above.

**Comment by bossie** [comment]
TODO:

- [ ] test with intended GeoVille STAC API
- [x] test with and without bands filter
- [ ] without bands filter, position of band B8A differs between STAC Item and STAC API (sorts by asset ID even though STAC Item has an ordered eo:bands summary)
- [ ] support STAC API Collection with multi-band assets
- [ ] run `FileLayerProvider` tests
- [ ] get `NoDataAvailableException` in there
- [ ] use additional metadata in Collection e.g. extent etc to optimize (is currently treated as a Catalog)
- [ ] handle TODOs in code
- [ ] move catalog crawling to Scala side and retire `FixedFeaturesOpenSearchClient`
- [ ] clean up

**Comment by bossie** [comment]
With the temporary catalog workarounds applied, this batch job runs successfully and produces 3 GeoTiffs with 3 bands each:

```python
connection = openeo.connect("openeo-3-1.openeo-vlcc-prod").authenticate_oidc()

data_cube = (connection
             .load_stac(url="https://vlcc.geoville.com/resto/collections/BVLPROBA_v1",
                        spatial_extent={"west": 20.579494542018466, "south": 54.31120577537291,
                                        "east": 20.631426035739594, "north": 54.33263361375995},
                        temporal_extent=["2019-01-01", "2021-12-31"],
                        bands=["band1", "band2", "band3"])
             .save_result("GTiff"))

job = data_cube.execute_batch()
job.download_results("/tmp")

# openEO_2019-01-01Z.tif
# openEO_2020-01-01Z.tif
# openEO_2021-01-01Z.tif
```

**Comment by bossie** [comment]
As discussed: seeing as client-side filtering on Item properties tends to work better than the STAC API Filter extension (400 "Unknown property in filter" most of the time) it was decided to postpone this TODO.

**Comment by m-mohr** [comment]
Are you aware of the queryables endpoint, which you can use to retrieve the available properties for the filters?

**Comment by bossie** [comment]
This particular STAC API returns "additionalProperties": true but still rejects most properties.

**Comment by jdries** [comment]
done!
