### ISSUE TITLE
run udf's on executor only

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#404]

**Comment by soxofaan** [comment]
done

**Comment by soxofaan** [comment]
This new feature made some cropsar related integration tests fail because the cropsar related UDF, assuming it is running in driver, tried to do `SparkContext.getOrCreate()` and alike. This has been resolved already in cropsar implementation

In the meantime I still added in e4ca6d15056d05c58d6606eb74d1efe68c604937 a global feature flag (in `GpsBackendConfig`) to optionally allow running UDFs in driver process.
This feature flag should be removed at some point
