### ISSUE TITLE
raster_to_vector does not create touching polygons

### ISSUE THREAD

**Issue by JeroenVerstraelen** [Open-EO/openeo-geopyspark-driver#576]
A user noticed a bug in raster_to_vector where neighboring pixels that do not have the same values are joined into one single polygon anyway. So an area that should produce e.g. 3 separate touching polygons produces one polygon instead.

**Comment by soxofaan** [comment]
as discussed, this is probably because user is working with pixel values in [0-1] range (probabilities), which are, I guess, rounded to integers before doing the polygon construction.

workaround is probably to scale the probabilities with, e.g. 100 or 1000 scaling factor, before passing it to raster_to_vector
