### ISSUE TITLE
support `export_workspace`  to static STAC

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#606]
See: https://github.com/Open-EO/openeo-processes/pull/485

I would like for us to be able to define a (static) STAC collection that should receive the job metadata, as opposed to only storing it under batch job results.

One of the first use cases would be to build a catalog of reference data extractions.

**Comment by jdries** [comment]
Constraint: the process that copies the (meta)data should not run as part of the batch job, to avoid that batch jobs require elevated privileges or credentials.

This means that implementing this as part of job_tracker or a nifi flow is perhaps the better alternative. 

Decision: just setup export to CF object storage, or perhaps allow for a Terrascope disk.

**Comment by bossie** [comment]
Current implementation:

`export_workspace` (#676) writes STAC (Collection and Item) metadata next to a job's output assets in a workspace; this STAC Collection (a path on disk) is readable with `load_stac`.

If it is mounted as a directory on disk, a bucket in object storage can also act as a workspace.

`export_workspace` takes a `merge` parameter that is essentially a subdirectory within a workspace; this can be used to avoid file overlap between jobs in the same workspace. Currently it will overwrite rather than merge with an existing STAC Collection.
