### ISSUE TITLE
add file name extension to result assets

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#66]
With VITO geopyspark backend, the standard batch jobs have a single output file, which is called "out" in the result listing (`GET /jobs/{jobid}/results`)
```python
{'assets': {'out': {'href': 'http://openeo-dev.vgt.vito.be/openeo/1.0/jobs/57da31da-7fd4-463a-9d7d-c9c51646b6a4/results/out',
   'type': 'application/octet-stream'}},
```

it would be better for the user experience when downloading to add a proper extension (.tiff, .json, ...)

**Comment by jdries** [comment]
This is being fixed: batch jobs will be able to use a file name that is more relevant for the used format.
Metadata will properly describe what is what.

**Comment by m-mohr** [comment]
Hmm, it doesn't seem to be fixed. I still get "out" for GeoTiff as a filename. The filename itself is not really an issue for me, but the "application/octet-stream" media type both in STAC and the headers is a real issue as then clients can't detect what media type it really is, which for me breaks visualization support in the Browser. So right now I can only offer all files from VITO as download instead of visualizing them on a map.

**Comment by jdries** [comment]
I believe this should now be fixed entirely, this commit is also relevant:
https://github.com/Open-EO/openeo-geopyspark-driver/commit/f406ac7d13ddf80e50bdfc979ff5e3dc13fbfbf9
