### ISSUE TITLE
ETL: support organization id based reporting

### ISSUE THREAD

**Issue by soxofaan** [Open-EO/openeo-geopyspark-driver#671]
Discussed with @JanssenBrm: we want to introduce an "organization" concept in the ETL API resource reporting, so that users that are part of multiple organizations/projects can explicitly specify the desired organization that resource usage should be reported under.

- user specifies organization_id as job option (well known feature of batch jobs, also possible for sync jobs) during job creation time
- organisation_id should be included in ETL resource reporting request (not supported yet)
- ideally, organization_id should be checked for validity at job creation time. ETL endpoint to be added

**Comment by soxofaan** [comment]
> and why not using the 'plan' option for this? 

In our discussion, @JanssenBrm  mentioned also another thing on the roadmap that feels more suited for the "plan" field: distinction between different kind of credits: free, commercial, ..., . 
The "organization" concept matches a lot worse with how "plan" is currently described in the spec, e.g. orgs will be specific per user, while plans are expected to be declared globally in the capabilities doc.

**Comment by soxofaan** [comment]
this ticket is currently blocked: this feature first has to be implemented in ETL API : https://jira.vito.be/browse/MKTP-379

**Comment by JeroenVerstraelen** [comment]
@soxofaan

**Comment by soxofaan** [comment]
hi @rahmandawibowo-vito ,

apologies for the slow response, the notification of this apparently slipped under my radar

> The OpenEO needs to check if the job can be executed based on org ID using the new endpoint

Does this endpoint just check if a user is within the org, or does it also check if there is minimum amount of credits?

> If the OpenEO sends an org ID on the reporting request (sync job or batch job), the ETL-API will try to deduct credits based on the org ID (even though user ID is also present on the payload). The deduction will be a success only if the user is the member of the org. The org ID should be the same with the one on the 1st point.

Is there a fallback mechanism when the user is not a member of the org, e.g. deduct the user's personal balance? Otherwise there is a loophole that can be exploited: start a heavy job while being member, and temporarily unregister as org member around the time the job finishes -> nobody is charged


> e.g. the job can be executed on VITO org, but when deducting credits will be using other org that doesn't have sufficient credits

I'm not sure I understand why this is a problem specifically to the org-based reporting. You always have that problem, right, even with user-based reporting?


> `GET /organizations/orgId/permissions`
> `POST /resources  > orgId`

This `orgId` is apperently a number: how can the user figure out this id? Is that available somewhere on eoplaza?

**Comment by rahmandawibowo-vito** [comment]
Hi @soxofaan, yes the orgId information should be provided by the eoplaza. But I just realized that we don't display this info yet to the user. I think I will add this orgId somewhere in the eoplaza so that we can make a guideline/docs on this.

**Comment by rahmanda** [comment]
Apologize for the late follow up. Here are the necessary info to move forward:
> Does this endpoint just check if a user is within the org, or does it also check if there is minimum amount of credits?
When the credit check is supplied with the orgId, they will check whether the organization has enough credits. If the user is not part of the org, the credit check will return false.

> Is there a fallback mechanism when the user is not a member of the org, e.g. deduct the user's personal balance? Otherwise there is a loophole that can be exploited: start a heavy job while being member, and temporarily unregister as org member around the time the job finishes -> nobody is charged

Yes the validation is in place. If the user tried to input orgId while not being a member, the ETL-API will deduct the credits from their active billing org.

> I'm not sure I understand why this is a problem specifically to the org-based reporting. You always have that problem, right, even with user-based reporting?

Yes that's true because in normal flow, we always deduct credits from their active org and we cannot make sure the active org is the same with the one used for running the job. I was just making sure that when the user is explicitly running a job with orgId on OpenEO, this exact same orgId should also be sent along with the payload for reporting the job. 

The user can get the orgId from EOplaza by visiting their organization detail page (terrascope: https://portal.terrascope.be/profile/organisation, cdse: https://marketplace-portal.dataspace.copernicus.eu/profile/organisation).

![image](https://github.com/user-attachments/assets/ad7c00bb-8200-40f2-8f6b-7aa423d48a11).

cc: @soxofaan @JeroenVerstraelen

**Comment by soxofaan** [comment]
ok thanks for that info, I think I can work from that at the moment

**Comment by soxofaan** [comment]
also added minimal docs at https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/docs/etl-organization-id.md

**Comment by soxofaan** [comment]
I just confirmed it also works with batch jobs on CDSE dev deploy (which has `'openeo-geopyspark': '0.53.0a1.dev20241210+2338'`), with something like this:

```
job = cdse.create_job(
    pg,
    additional={
        "etl_organization_id": etl_organization_id,
    },
)
```
