### ISSUE TITLE
export_workspace: support STAC merge

### ISSUE THREAD

**Issue by jdries** [Open-EO/openeo-geopyspark-driver#677]
export_workspace has a 'merge' option. When set, the STAC metadata of the result should be merged into the STAC metadata that is already present in the workspace.
This needs to take details into account such as:
- update of spatiotemporal extent
- handling conflicting properties
- overwriting existing products
- directory hierarchy

**Comment by bossie** [comment]
As discussed:

- by default, items will be overwritten rather than appended (item IDs match asset filenames like in the job results response from the web API);
- it is then the responsibility of the client to specify a `filename_prefix` to avoid overwriting items/assets.

**Comment by bossie** [comment]
Before, the `merge` parameter was interpreted as a [directory/prefix](https://github.com/Open-EO/openeo-processes/issues/467). Actually trying to merge into an existing STAC Collection made it apparent that it should point to an actual STAC resource (i.e. a Collection) instead, as the process description specifies.

Seeing as we have already have (internal) users of `export_workspace`, this matter of backwards compatibility needs to be addressed, for example by a grace period with a job_option.

**Comment by bossie** [comment]
TODO: support behavior of #877 that was added in the meanwhile. Is disconnecting the asset hrefs from the STAC hrefs key here? TBC

**Comment by bossie** [comment]
To be looked into how well item ID == asset _path_ scales.

While workable in the case of a single batch job (i.e. `/jobs/{job_id}/results` response), appending using unique item IDs (might also include a reference to the batch job) rather than overwriting:

- is probably less confusing/error prone if multiple batch jobs are merged together;
- might also remove some assumptions in the current implementation.

It is then the responsibility of the workspace owner to remove unwanted items (in an out-of-band manner).
