### ISSUE TITLE
CreoDIAS capabilities: production=true but description says it's "unstable"

### ISSUE THREAD

**Issue by christophfriedrich** [Open-EO/openeo-geopyspark-driver#68]
The CreoDIAS driver's capability response at https://openeo.creo.vito.be/openeo/1.0/ has the `production` flag set to `true`, yet the free text under `description` says, as the very first thing and in CAPITAL letters, that this backend is "[UNSTABLE]". Could you align the two?

https://github.com/Open-EO/openeo-geopyspark-driver/blob/8c02c8d6fecddcc9b587dea28d6b85a5610f2b83/openeogeotrellis/deploy/kube.py#L66-L81

**Comment by jdries** [comment]
Hi Christoph, it's all about the interpretation of this flag. There simply is no 'production' openEO backend in existence, as it's too early for that. So we use it to indicate to the client which of the versions it should consider as production ready. This allows us to start supporting a version 1.1.0 for instance, with the production flag set to false.
So for us it's more like 'relative to all other versions, these are the ones we consider the most stable' rather than an absolute measure of production readiness (like TRL levels).

**Comment by christophfriedrich** [comment]
Thanks for the explanation, that sounds reasonable!
