### ISSUE TITLE
Sentinel 2 reduce dimension mean data type

### ISSUE THREAD

**Issue by theroggy** [Open-EO/openeo-geopyspark-driver#835]
It seems that in januari reduce_dimension with reducer `mean` on the `int16` bands of sentinel2 images, resulted in an int16 GeoTiff result. Now, as far as I know without significant changes to our code this results in a float32 GeoTiff.

Has there been a change that can explain this?

I tried apply("int") on the result, but then this leads to an int32 being saved. Is there a way to get back an int16 geotiff without rereading and resaving him locally?

@KriWay-LV

**Comment by jdries** [comment]
Indeed, there was an important change (in march) to switch to floating point datatypes faster, avoiding that users get unexpected results because of data type limits. It was announced here:
https://discuss.eodc.eu/t/terrascope-backend-upgrade/542/7
https://github.com/Open-EO/openeo-geopyspark-driver/blob/907135bbe50ae2e40995f285064b7c2029774b2a/CHANGELOG.md#improved-datatype-conversion

But you can indeed force it back to int16:
`
cube.linear_scale_range(0, 10000, 0, 10000)
`
The exact datatype is inferred from the ranges. The backend does this as a side effect, because openEO does not really have explicit support for data types.

**Comment by theroggy** [comment]
Thanks! Works fine. I subscribed to the "news" section on discuss.eodc.eu.
